# Generated by Django 3.2.7 on 2021-09-15 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_rename_image_answer_answer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_image',
        ),
    ]
